import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/main.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", inter.variable)}>
      <body className="min-h-full w-full max-w-[1280px] mx-auto flex flex-col p-[5%] sm:p-4 ">
        {children}
      </body>
    </html>
  );
}
